In [1]:
# importing required libraries
import numpy as np
import pandas as pd

from sklearn.metrics import  mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

In [2]:
# reading training data from csv
iotdata = pd.read_csv("IOT_Assignment_2_data_regression_sensor_range.csv")
iotdata.head()

Humidity(%)  Temperature(°C)  WaterFlow(%)
0    25.045045        76.856857     67.432607
1     8.880881        31.771772      0.000000
2    24.956957        75.735736     66.105904
3    40.328328        88.308308      0.000000
4    38.742743        57.157157      0.000000

In [3]:
# printing shape of datasdet
iotdata.shape

(200, 3)

In [4]:
# checking for null or missing values in dataset
iotdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Humidity(%)      200 non-null    float64
 1   Temperature(°C)  200 non-null    float64
 2   WaterFlow(%)     200 non-null    float64
dtypes: float64(3)
memory usage: 4.8 KB


In [5]:
# separating dependent and independent attributes
X, y = iotdata.drop(columns="WaterFlow(%)"), iotdata["WaterFlow(%)"]
X.head(2), y.head(2)

(   Humidity(%)  Temperature(°C)
 0    25.045045        76.856857
 1     8.880881        31.771772,
 0    67.432607
 1     0.000000
 Name: WaterFlow(%), dtype: float64)

In [32]:
# split dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
X_train.shape, y_train.shape

((140, 2), (140,))

In [33]:
# model designing
mlp = MLPRegressor(hidden_layer_sizes=(3, 3), activation="relu", max_iter=20000)

mlp.fit(X_train, y_train)
pred = mlp.predict(X_test)

print("R2 score: ", r2_score(pred, y_test))
print("Mean Squared Error: ", mean_squared_error(pred, y_test))

R2 score:  0.7086823344328602
Mean Squared Error:  289.17763556760406


In [34]:
# extracting trained coefficients and intercepts
mlp.coefs_, mlp.intercepts_

([array([[-1.62512530e+00, -1.25647664e-01,  1.27342808e-03],
         [ 1.30754050e+00,  2.22294306e-02, -3.04635327e-02]]),
  array([[-1.38935249e-063,  6.38250945e-001, -2.01915742e-100],
         [ 6.21648834e-138, -3.83377990e+000,  4.18442800e-053],
         [ 1.28126468e-047, -8.50167740e-002, -2.64964214e-041]]),
  array([[ 1.65620559e-44],
         [ 2.24336547e+00],
         [-1.29960621e-36]])],
 [array([-3.03832916,  4.55312463,  0.21453741]),
  array([-0.67005969, -1.71418843, -0.53256778]),
  array([0.10515677])])

In [36]:
# defining Relu Activation Function
def relu(x):
    return np.maximum(x, 0)

In [57]:
# predicting percentage waterflow for a sample
np.dot(relu(np.dot(relu(np.dot(np.array([[23, 50.5]]), w[0]) + b[0]), w[1]) + b[1]), w[2]) + b[2]

array([[8.97574689]])

In [40]:
# just testing prediction and test data
pd.DataFrame({"pred":pred, "ytest": y_test})

pred       ytest
116   36.306835    0.000000
40     0.105157    0.000000
167    0.105157    0.000000
110    0.930743   27.963620
134    0.669522    0.000000
175    0.105157    0.000000
168    7.148083    0.000000
2     48.957888   66.105904
8    102.161492  100.000000
174   58.885522   77.142561
74     0.105157    0.000000
177   11.488554    0.000000
146    0.105157    0.000000
155    0.105157    0.000000
11     0.105157    0.000000
30    87.176408   92.785435
14     0.105157    0.000000
46     1.389475   28.312213
120   29.095225    0.000000
112    0.105157    0.000000
181   45.934912   62.906293
115    0.105157    0.000000
84     0.105157    0.000000
124   75.858602   88.741787
162   72.546790   85.433737
52     0.105157   22.111300
137    0.105157    0.000000
119    8.154159   33.979026
17    16.651792    0.000000
24     0.105157    0.000000
142   39.823553   54.957880
198   30.039015    0.000000
71    24.650323    0.000000
190   90.174348   91.859900
187   73.266675   81.384543
199   22.177744    0.000000
16     0.105157    0.000000
164   56.008898    0.000000
92    57.136967   78.168944
58     0.105157    0.000000
5      0.105157    0.000000
127   47.812857   61.813370
100    0.105157    0.000000
139   64.321030   80.729431
0     50.732701   67.432607
194    0.105157    0.000000
37    67.790593   76.514940
122    0.105157    0.000000
18     0.105157    0.000000
132   17.113577   50.163237
85     0.105157    0.000000
45     0.105157    0.000000
66    47.069767   72.610376
170    0.105157    0.000000
143    0.105157    0.000000
49   100.919910   99.155704
34    68.517263   77.395564
171   45.744323    0.000000
125   69.402363   84.104938
144    0.105157    0.000000